const styles = {
  appShell:             { minHeight: "100vh", background: "#0E0E10", fontFamily: "'Source Serif Pro', Georgia, serif", color: "#E8E4D8", position: "relative" },
  topBar:               { display: "flex", alignItems: "center", gap: 14, padding: "14px 24px", background: "#1C2B4A", color: "#F5F2E8", borderBottom: "4px solid #C9A227", position: "relative", zIndex: 10 },
  seal:                 { width: 34, height: 34, borderRadius: "50%", border: "2px solid #C9A227", display: "flex", alignItems: "center", justifyContent: "center", color: "#C9A227", fontSize: 16, flexShrink: 0 },
  topBarTitle:          { fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 15, letterSpacing: "0.08em" },
  topBarSub:            { fontSize: 12, opacity: 0.75, letterSpacing: "0.03em" },
  monthChip:            { textAlign: "right", border: "1px solid #C9A227", borderRadius: 4, padding: "6px 12px" },
  monthChipLabel:       { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, letterSpacing: "0.1em", color: "#C9A227" },
  monthChipName:        { fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 15 },
  mapStage:             { position: "relative", minHeight: "calc(100vh - 64px)", overflow: "hidden" },
  mapSvg:               { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", display: "block" },
  seatArcWidget:        { position: "absolute", top: 16, left: 16, width: 280, background: "rgba(15,15,18,0.82)", border: "1px solid #3A3A40", borderRadius: 6, padding: "10px 12px 8px", backdropFilter: "blur(4px)", zIndex: 5 },
  seatArcWidgetHeader:  { fontFamily: "'JetBrains Mono', monospace", fontSize: 9.5, letterSpacing: "0.12em", color: "#C9A227", marginBottom: 4 },
  legendOverlay:        { position: "absolute", bottom: 16, left: 16, background: "rgba(15,15,18,0.82)", border: "1px solid #3A3A40", borderRadius: 6, padding: "12px 16px", backdropFilter: "blur(4px)", zIndex: 5 },
  caseFileOverlay:      { position: "absolute", top: 16, right: 16, width: 260, zIndex: 25 },
  chamberPromptOverlay: { position: "absolute", bottom: 90, left: "50%", transform: "translateX(-50%)", background: "rgba(15,15,18,0.85)", border: "1px solid #3A3A40", borderRadius: 6, padding: "8px 16px", fontSize: 13.5, fontStyle: "italic", color: "#C8C4B8", zIndex: 5, whiteSpace: "nowrap" },
  legendWrap:           { display: "flex", gap: 20, flexWrap: "wrap" },
  legendCol:            { display: "flex", flexDirection: "column", gap: 5, minWidth: 130 },
  legendHeader:         { fontFamily: "'JetBrains Mono', monospace", fontSize: 9.5, letterSpacing: "0.1em", color: "#C9A227", marginBottom: 2 },
  legendRow:            { display: "flex", alignItems: "center", gap: 6 },
  legendDot:            { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
  legendLabel:          { fontSize: 10.5, color: "#C8C4B8" },
  caseFile:             { background: "rgba(15,15,18,0.82)", border: "1px solid #3A3A40", borderRadius: 6, padding: "14px 14px 16px", backdropFilter: "blur(4px)" },
  caseFileHeader:       { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, letterSpacing: "0.15em", color: "#8B1A1A", borderBottom: "1px solid #3A3A40", paddingBottom: 7, marginBottom: 12 },
  cfSection:            { marginBottom: 15 },
  cfLabel:              { fontFamily: "'Roboto Slab', Georgia, serif", fontSize: 11.5, fontWeight: 700, marginBottom: 7, color: "#E8E4D8" },
  gaugeOuter:           { position: "relative", height: 18, background: "#2A2A30", borderRadius: 3, overflow: "hidden" },
  gaugeFill:            { height: "100%" },
  gaugeText:            { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontFamily: "'JetBrains Mono', monospace", fontWeight: 700, color: "#fff", textShadow: "0 1px 2px rgba(0,0,0,0.6)" },
  ledgerLine:           { display: "flex", alignItems: "baseline", gap: 7 },
  ledgerNum:            { fontFamily: "'JetBrains Mono', monospace", fontSize: 18, fontWeight: 700, color: "#5FAF7E" },
  ledgerUnit:           { fontSize: 10.5, color: "#888" },
  relRow:               { marginBottom: 9 },
  relName:              { fontSize: 11.5, fontWeight: 700, borderLeft: "3px solid", paddingLeft: 6, marginBottom: 3 },
  miniBarWrap:          { display: "flex", alignItems: "center", gap: 5, marginBottom: 2 },
  miniBarLabel:         { fontFamily: "'JetBrains Mono', monospace", fontSize: 8.5, width: 34, color: "#777", letterSpacing: "0.03em" },
  miniBarTrack:         { flex: 1, height: 5, background: "#2A2A30", borderRadius: 3, overflow: "hidden" },
  miniBarFill:          { height: "100%", background: "#5B7FE0" },
  chitRow:              { display: "flex", flexWrap: "wrap", gap: 5 },
  chit:                 { border: "1.5px solid", borderRadius: 3, padding: "3px 7px", fontSize: 10, fontFamily: "'JetBrains Mono', monospace" },
  dim:                  { fontSize: 11, color: "#777", fontStyle: "italic" },
  sceneOverlay:         { position: "fixed", inset: 0, background: "transparent", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 50, pointerEvents: "none" },
  sceneOverlayInner:    { width: "100%", maxWidth: 640, maxHeight: "88vh", overflowY: "auto", pointerEvents: "auto" },
  sceneCard:            { background: "#FFFDF8", color: "#3D3D3D", border: "1px solid #D8D2C0", borderRadius: 4, boxShadow: "0 8px 30px rgba(0,0,0,0.4)", overflow: "hidden" },
  speakerTag:           { padding: "14px 20px", color: "#FFFDF8" },
  speakerName:          { fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 17 },
  speakerRole:          { fontSize: 12, opacity: 0.85, marginTop: 2, fontFamily: "'JetBrains Mono', monospace", letterSpacing: "0.03em" },
  transcriptText:       { padding: "20px 24px 8px" },
  line:                 { fontSize: 16, lineHeight: 1.65, margin: "0 0 14px" },
  choiceList:           { padding: "8px 20px 22px", display: "flex", flexDirection: "column", gap: 8 },
  choiceBtn:            { textAlign: "left", background: "#F5F2E8", border: "1px solid #C8C0A8", borderRadius: 3, padding: "12px 14px", fontFamily: "'Source Serif Pro', Georgia, serif", fontSize: 14.5, color: "#1C2B4A", cursor: "pointer" },
  choiceMark:           { color: "#8B1A1A", fontWeight: 700, marginRight: 6 },
  daisLabel:            { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: "0.12em", color: "#8B1A1A", padding: "0 24px", marginTop: 8 },
  offerTable:           { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, padding: "10px 20px" },
  offerChit:            { textAlign: "left", background: "#FFFDF8", border: "2px solid #1C2B4A", borderRadius: 4, padding: "10px 12px", cursor: "pointer" },
  offerChitActive:      { background: "#1C2B4A", color: "#FFFDF8" },
  offerChitDisabled:    { opacity: 0.35, cursor: "not-allowed", borderColor: "#999" },
  offerChitLabel:       { fontSize: 13.5, fontWeight: 600, lineHeight: 1.3 },
  offerChitCost:        { fontFamily: "'JetBrains Mono', monospace", fontSize: 10.5, opacity: 0.75, marginTop: 4 },
  projectionBar:        { padding: "12px 24px 4px" },
  projectionLabel:      { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, letterSpacing: "0.1em", color: "#3D3D3D", opacity: 0.7 },
  projectionTrack:      { height: 10, background: "#E5DFCC", borderRadius: 5, marginTop: 6, overflow: "hidden" },
  projectionFill:       { height: "100%", transition: "width 0.25s ease" },
  projectionNote:       { fontSize: 13, marginTop: 8, fontStyle: "italic", color: "#555" },
  submitBtn:            { background: "#2D5C3E", color: "#FFFDF8", border: "none", borderRadius: 3, padding: "13px 14px", fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 14, letterSpacing: "0.04em", cursor: "pointer" },
  actionBar:            { position: "fixed", bottom: 0, left: 0, right: 0, background: "#1C2B4A", borderTop: "3px solid #C9A227", padding: "14px 24px", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap", zIndex: 40 },
  actionBarText:        { fontSize: 14, color: "#F5F2E8", flex: 1, minWidth: 200 },
  actionBarBtn:         { background: "#C9A227", color: "#1C2B4A", border: "none", borderRadius: 3, padding: "10px 18px", fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 13.5, cursor: "pointer", whiteSpace: "nowrap" },
  tabRow:               { display: "flex", gap: 3, marginBottom: 10, borderBottom: "1px solid #2A2A30", paddingBottom: 8 },
  tabBtn:               { flex: 1, background: "transparent", border: "1px solid #2A2A30", borderRadius: 3, padding: "4px 0", fontFamily: "'JetBrains Mono', monospace", fontSize: 9, letterSpacing: "0.08em", color: "#666", cursor: "pointer" },
  tabBtnActive:         { background: "#1C2B4A", color: "#C9A227", borderColor: "#1C2B4A" },
  districtTooltip:      { position: "fixed", background: "rgba(14,14,16,0.96)", border: "1px solid #3A3A40", borderRadius: 5, padding: "9px 13px", pointerEvents: "none", zIndex: 200, minWidth: 170, boxShadow: "0 4px 18px rgba(0,0,0,0.5)" },
  ttName:               { fontFamily: "'Roboto Slab', Georgia, serif", fontWeight: 700, fontSize: 13, color: "#F5F2E8", marginBottom: 3 },
  ttFaction:            { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, marginBottom: 3 },
  ttVoteYes:            { fontSize: 10.5, color: "#2D5C3E", fontWeight: 700, marginBottom: 3 },
  ttVoteNo:             { fontSize: 10.5, color: "#8B1A1A", fontWeight: 700, marginBottom: 3 },
  ttTerm:               { fontSize: 10.5, marginTop: 2 },
  factionApprRow:       { display: "flex", alignItems: "center", gap: 5, marginBottom: 5 },
  factionApprDot:       { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
  factionApprName:      { fontFamily: "'JetBrains Mono', monospace", fontSize: 8.5, color: "#888", width: 72, flexShrink: 0, overflow: "hidden", whiteSpace: "nowrap" },
  factionApprTrack:     { flex: 1, height: 5, background: "#2A2A30", borderRadius: 3, overflow: "hidden" },
  factionApprFill:      { height: "100%", opacity: 0.75 },
  factionApprPct:       { fontFamily: "'JetBrains Mono', monospace", fontSize: 8.5, color: "#888", width: 26, textAlign: "right", flexShrink: 0 },
};

export default styles;
